/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Font;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EmpManage extends javax.swing.JFrame {

    Connection c = DB.DBConnect.getConnection();
    ResultSet rs = null;
    PreparedStatement psm;
    DefaultTableModel model;
    String sql = "";
    public Home1 hm;
    
            
    public EmpManage() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        
        Font f = new Font("Saysettha OT", Font.PLAIN, 15);
        tbEmp.getTableHeader().setFont(f);
        
        model = (DefaultTableModel) tbEmp.getModel();
        showData();
    }

    public void showData(){
        try {
            int rowidx = tbEmp.getRowCount()-1;
            
            while(rowidx>-1){
                model.removeRow(rowidx--);
            }
            sql = "select * from tb_employee";
            
            rs = c.createStatement().executeQuery(sql);
            
            while(rs.next()){
                String [] data = {rs.getString("EmpId"),
                                  rs.getString("EmpName"),
                                  rs.getString("EmpSurname"),
                                  rs.getString("Gender"),
                                  rs.getString("DOB"),
                                  rs.getString("Village"),
                                  rs.getString("City"),
                                  rs.getString("Province"),
                                  rs.getString("Tel"),
                                  rs.getString("AccountType")};
                model.addRow(data);
            }
            rs.close();
            tbEmp.setModel(model);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmp = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Saysettha OT", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ການ​ຈັດ​ການ​ພະ​ນັ​ກ​ງານ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 340, 90));

        btnAdd.setBackground(new java.awt.Color(51, 255, 204));
        btnAdd.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/add_to_database_50px.png"))); // NOI18N
        btnAdd.setText("ເພີ່ມ");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 160, 70));

        btnDelete.setBackground(new java.awt.Color(0, 255, 204));
        btnDelete.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/clear_symbol_50px.png"))); // NOI18N
        btnDelete.setText("ລຶບ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 50, 170, 70));

        btnUpdate.setBackground(new java.awt.Color(0, 255, 204));
        btnUpdate.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/edit_property_50px.png"))); // NOI18N
        btnUpdate.setText("ແກ້​ໄຂ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, 190, 70));

        btnBack.setBackground(new java.awt.Color(0, 255, 204));
        btnBack.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnBack.setText("ກັບ​ຄືນ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1160, 50, 170, 70));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Logo4Empfrm.png"))); // NOI18N
        jLabel2.setText("Logo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 210, 180));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1390, 190));

        tbEmp.setBackground(new java.awt.Color(255, 255, 102));
        tbEmp.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        tbEmp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ລະ​ຫັດ", "​ຊື່", "​ນາມ​ສະ​ກຸນ", "ເພດ", "ວດ​ປ ເກີດ", "ບ້ານ", "ເມືອງ", "ແຂວງ", "ເບີ​ໂທ", "ສະ​ຖາ​ນະ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEmp.setSelectionBackground(new java.awt.Color(0, 255, 102));
        tbEmp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEmpMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbEmp);
        if (tbEmp.getColumnModel().getColumnCount() > 0) {
            tbEmp.getColumnModel().getColumn(8).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1370, 520));

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1380, 710));

        setBounds(0, 0, 1385, 846);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
     AddEmp1 ep1=  new AddEmp1(this, true);
     ep1.emp=this;
     ep1.show();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            int rowclick = tbEmp.getSelectedRow();
            
            if(rowclick != -1){
               if(JOptionPane.showConfirmDialog(this, "Do you want to delete?", "Warning!: Action required", 
                                                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE) == 0){
                   
                   sql = "delete from tb_employee where EmpId=?";
                   
                   psm = c.prepareStatement(sql);
                   psm.setInt(1, Integer.parseInt(model.getValueAt(rowclick, 0).toString()));
                  
                   if(psm.executeUpdate() != -1){
                       showData();
                   }
               }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        UpdateEmp ue = new UpdateEmp(this, true);
//        ue.em=this;
//        ue.show();
        try {
            int rowclick = tbEmp.getSelectedRow();
            if (rowclick > -1) {
                //Get Picture Error width, height must Non-Zero
//                String stridx = tbEmp.getValueAt(rowclick, 0).toString();
//                sql = "select tb_employee.ProfilePic from tb_employee where EmpId=?";
//                psm = c.prepareStatement(sql);
//                psm.setString(1, stridx);
//                rs = psm.executeQuery();
//                if (rs.next()) {
//                    byte[] pic = rs.getBytes("ProfilePic");
//                    ImageIcon ico4 = new ImageIcon(pic);
//                    Image im2 = ico4.getImage().getScaledInstance(ue.lbAddPic.getWidth(), 
//                                                                  ue.lbAddPic.getHeight(), 
//                                                                  Image.SCALE_SMOOTH);
//                    ImageIcon ico5 = new ImageIcon(im2);
//                    ue.lbAddPic.setIcon(ico5);
//                }
//                rs.close();

                ue.txtEmpID.setText(tbEmp.getValueAt(rowclick, 0).toString());
                ue.txtName.setText(tbEmp.getValueAt(rowclick, 1).toString());
                ue.txtSurname.setText(tbEmp.getValueAt(rowclick, 2).toString());
                
                //Set Gender to radio button
                String gender = tbEmp.getValueAt(rowclick, 3).toString();
                if(gender.equals("ຊາຍ")){
                    ue.rbMale.setSelected(true);
                }else if(gender.equals("ຍິງ")){
                    ue.rbFemale.setSelected(true);
                }
                
                String acc = tbEmp.getValueAt(rowclick, 9).toString();
                if(acc.equals("Admin")){
                    ue.rbAdmin.setSelected(true);
                }else if(acc.equals("Employee")){
                    ue.rbEmp.setSelected(true);
                }
                
                ue.jDateChooser1.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(rowclick, 4)));
                ue.txtVillage.setText(tbEmp.getValueAt(rowclick, 5).toString());
                ue.txtCity.setText(tbEmp.getValueAt(rowclick, 6).toString());
                ue.txtProvince.setText(tbEmp.getValueAt(rowclick, 7).toString());
                ue.txtTel.setText(tbEmp.getValueAt(rowclick, 8).toString());

                ue.em = this;
                ue.show();
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void tbEmpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEmpMouseClicked
       
    }//GEN-LAST:event_tbEmpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmpManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmpManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public volatile javax.swing.JTable tbEmp;
    // End of variables declaration//GEN-END:variables
}
