/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Toto
 */
public class Import extends javax.swing.JDialog {

    String sql = "";
    Connection c = DB.DBConnect.getConnection();
    PreparedStatement psm;
    ResultSet rs=null;   
    public ProductManage pm;
    public PM4Emp pm4;
    ArrayList<String> Sup;
    DefaultTableModel model;
    
    public Import(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
        Font f = new Font("Saysettha OT", Font.PLAIN, 12);
        tbShowProductImport.getTableHeader().setFont(f);
        
        cbSup();
        model = (DefaultTableModel) tbShowProductImport.getModel();
        showProductImport("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DCImport = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        DCExp = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        cbSupp = new javax.swing.JComboBox<>();
        txtProductID = new javax.swing.JTextField();
        txtPN = new javax.swing.JTextField();
        txtQty = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbShowProductImport = new javax.swing.JTable();
        txtSearch = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnImport = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel1.setText("ລະ​ຫັດ​ສິນ​ຄ້າ:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 30));

        jLabel2.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel2.setText("ຊື່​ສິນ​ຄ້າ:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 165, 50, 30));

        jLabel3.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel3.setText("ຈຳ​ນວນ:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 50, 30));

        DCImport.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(DCImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 190, -1));

        jLabel4.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel4.setText("ວັນ​ທີ​ນຳ​ເຂົ້າ:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 80, 30));

        jLabel5.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel5.setText("ວັນ​ທີ​ຫມົດ​ອາ​ຍຸ:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, 30));

        DCExp.setBackground(new java.awt.Color(255, 153, 0));
        getContentPane().add(DCExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 190, -1));

        jLabel6.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel6.setText("ຜູ້​ສະ​ຫນອງ​ສິນ​ຄ້າ:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 385, -1, 30));

        cbSupp.setBackground(new java.awt.Color(255, 153, 0));
        cbSupp.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        cbSupp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSuppActionPerformed(evt);
            }
        });
        getContentPane().add(cbSupp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 386, 190, 30));

        txtProductID.setEditable(false);
        txtProductID.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        txtProductID.setText(" ");
        txtProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProductIDActionPerformed(evt);
            }
        });
        getContentPane().add(txtProductID, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 190, 30));

        txtPN.setEditable(false);
        txtPN.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        txtPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPNActionPerformed(evt);
            }
        });
        getContentPane().add(txtPN, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 190, 30));
        getContentPane().add(txtQty, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 190, 30));

        jLabel7.setBackground(new java.awt.Color(0, 255, 153));
        jLabel7.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("ສິນ​ຄ້າ​ນຳ​ເຂົ້າ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1180, 120));

        tbShowProductImport.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        tbShowProductImport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ລະ​ຫັດ", "ວັນ​ທີ​ນຳ​ເຂົ້າ", "ຈຳ​ນວນ", "ລະ​ຫັດ​ສິນ​ຄ້າ", "ຊື່່ສິນ​ຄ້າ", "ວັນ​ທີ​ຫມົດ​ອາ​ຍຸ", "ລະ​ຫັດ​ຜູ້​ສະ​ຫນອງ​ສິນ​ຄ້າ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbShowProductImport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbShowProductImportMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbShowProductImport);
        if (tbShowProductImport.getColumnModel().getColumnCount() > 0) {
            tbShowProductImport.getColumnModel().getColumn(0).setMinWidth(75);
            tbShowProductImport.getColumnModel().getColumn(0).setPreferredWidth(75);
            tbShowProductImport.getColumnModel().getColumn(0).setMaxWidth(75);
            tbShowProductImport.getColumnModel().getColumn(1).setMinWidth(100);
            tbShowProductImport.getColumnModel().getColumn(1).setPreferredWidth(100);
            tbShowProductImport.getColumnModel().getColumn(1).setMaxWidth(100);
            tbShowProductImport.getColumnModel().getColumn(2).setMinWidth(75);
            tbShowProductImport.getColumnModel().getColumn(2).setPreferredWidth(75);
            tbShowProductImport.getColumnModel().getColumn(2).setMaxWidth(75);
            tbShowProductImport.getColumnModel().getColumn(3).setMinWidth(75);
            tbShowProductImport.getColumnModel().getColumn(3).setPreferredWidth(75);
            tbShowProductImport.getColumnModel().getColumn(3).setMaxWidth(75);
            tbShowProductImport.getColumnModel().getColumn(4).setMinWidth(150);
            tbShowProductImport.getColumnModel().getColumn(4).setPreferredWidth(150);
            tbShowProductImport.getColumnModel().getColumn(4).setMaxWidth(150);
            tbShowProductImport.getColumnModel().getColumn(5).setMinWidth(100);
            tbShowProductImport.getColumnModel().getColumn(5).setPreferredWidth(100);
            tbShowProductImport.getColumnModel().getColumn(5).setMaxWidth(100);
            tbShowProductImport.getColumnModel().getColumn(6).setMinWidth(150);
            tbShowProductImport.getColumnModel().getColumn(6).setPreferredWidth(150);
            tbShowProductImport.getColumnModel().getColumn(6).setMaxWidth(150);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, 710, 480));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        getContentPane().add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 710, 40));

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnImport.setBackground(new java.awt.Color(0, 255, 255));
        btnImport.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnImport.setText("ນຳ​ເຂົ້າ");
        btnImport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportActionPerformed(evt);
            }
        });
        jPanel1.add(btnImport, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, 160, 50));

        btnDelete.setBackground(new java.awt.Color(0, 255, 255));
        btnDelete.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnDelete.setText("ລຶບ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 170, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1180, 660));

        setSize(new java.awt.Dimension(1155, 687));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPNActionPerformed

    private void btnImportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportActionPerformed
        try {
             sql = "insert into tb_import values(0,?,?,?,?,?)";
            psm = c.prepareStatement(sql);
            psm.setString(1, new SimpleDateFormat("yyyy-MM-dd").format(DCImport.getDate()));
            psm.setInt(2, Integer.parseInt(txtQty.getText()));
            psm.setInt(3, Integer.parseInt(txtProductID.getText()));
            psm.setString(4, new SimpleDateFormat("yyyy-MM-dd").format(DCExp.getDate()));
            psm.setInt(5, Integer.parseInt(Sup.get(cbSupp.getSelectedIndex())));
            

            if(psm.executeUpdate() != -1){
                sql = "UPDATE tb_product SET StockQty=(StockQty+?) where PId=?";
                psm = c.prepareStatement(sql);
                psm.setString(1, txtQty.getText());
                psm.setInt(2, Integer.parseInt(txtProductID.getText()));
                psm.executeUpdate();
                JOptionPane.showMessageDialog(null, "Done!","", JOptionPane.INFORMATION_MESSAGE);
                txtQty.setText("");
                DCImport.setDate(null);
                DCExp.setDate(null);
                showProductImport("");
            }          
            pm.showProduct("");
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnImportActionPerformed

    private void tbShowProductImportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbShowProductImportMouseClicked

        try {
            int idx = tbShowProductImport.getSelectedRow();

            
            DCImport.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(idx, 1)));
            txtQty.setText(tbShowProductImport.getValueAt(idx, 2).toString());           
            txtProductID.setText(tbShowProductImport.getValueAt(idx, 3).toString());
            txtPN.setText(tbShowProductImport.getValueAt(idx, 4).toString());
            DCExp.setDate(new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(idx, 5)));
            cbSupp.setSelectedItem(tbShowProductImport.getValueAt(idx, 6).toString());

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tbShowProductImportMouseClicked

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        showProductImport(txtSearch.getText());
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            sql = "delete from tb_import where ImpId=?";

            psm = c.prepareStatement(sql);
            psm.setInt(1, Integer.parseInt(tbShowProductImport.getValueAt(tbShowProductImport.getSelectedRow(), 0).toString()));
            

            if(psm.executeUpdate() != -1){
                sql = "UPDATE tb_product SET StockQty=(StockQty-?) where PId=?";
                psm = c.prepareStatement(sql);
                psm.setString(1, txtQty.getText());
                psm.setInt(2, Integer.parseInt(txtProductID.getText()));
                psm.executeUpdate();
                JOptionPane.showMessageDialog(this, "Deleted this product!", "Action Done!", JOptionPane.INFORMATION_MESSAGE);
                showProductImport("");
                    pm.showProduct("");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cbSuppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSuppActionPerformed
        if(cbSupp.getSelectedItem().equals("Custom Supplier")){
            AddSupplier as = new AddSupplier(null, true);
            as.ip=this;
            as.show();
        }
    }//GEN-LAST:event_cbSuppActionPerformed

    private void txtProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProductIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProductIDActionPerformed

        public void cbSup(){
        try {
            sql = "select * from tb_supplier";
            
            cbSupp.removeAllItems();
            Sup = new ArrayList<String>();
            rs = c.createStatement().executeQuery(sql);
            
            while (rs.next()){
                    cbSupp.addItem(rs.getString("SName"));
                    Sup.add(rs.getString("SId"));
            }
            cbSupp.addItem("Custom Supplier");
  
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        
         public void showProductImport(String search){
        try {
            model.getDataVector().removeAllElements();
            if (search.equals("")) {

                sql = "SELECT tb_import.ImpId, tb_import.ImpDate, tb_import.Quantity, "
                        + "tb_product.PId, tb_product.PName, tb_import.ExpirationDate, tb_supplier.SId "
                        + "FROM tb_import INNER JOIN tb_product ON tb_product.PId = tb_import.ProId "
                        + "INNER JOIN tb_supplier ON tb_supplier.SId = tb_import.SuppId";
            } else {
                sql = "SELECT tb_import.ImpId, tb_import.ImpDate, tb_import.Quantity, "
                        + "tb_product.PId,tb_product.PName, tb_import.ExpirationDate, tb_supplier.SId "
                        + "FROM tb_import INNER JOIN tb_product ON tb_product.PId = tb_import.ProId "
                        + "INNER JOIN tb_supplier ON tb_supplier.SId = tb_import.SuppId"
                        + " where PId Like '%" + txtSearch.getText() + "%' or "
                        + "PName Like '%" + txtSearch.getText() + "%' or "
                        + "ImpDate Like '%" + txtSearch.getText() + "%' or "
                        + "ExpirationDate Like '%" + txtSearch.getText() + "%' or "
                        + "SId Like '%" + txtSearch.getText() + "%' or "
                        + "Quantity Like '%" + txtSearch.getText() + "%'";
            }
            rs = c.createStatement().executeQuery(sql);
            
            while(rs.next()){
                String [] data = {rs.getString("ImpId"),
                rs.getString("ImpDate"),
                rs.getString("Quantity"),
                rs.getString("PId"),
                rs.getString("PName"),
                rs.getString("ExpirationDate"),
                rs.getString("SId")};
 
                model.addRow(data);
            }
            rs.close();
            tbShowProductImport.setModel(model);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Import.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Import dialog = new Import(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DCExp;
    private com.toedter.calendar.JDateChooser DCImport;
    public javax.swing.JButton btnDelete;
    private javax.swing.JButton btnImport;
    private javax.swing.JComboBox<String> cbSupp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbShowProductImport;
    public javax.swing.JTextField txtPN;
    public javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
