/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.text.SimpleDateFormat;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Toto
 */
public class UpdateEmp extends javax.swing.JDialog {

    Connection c = DB.DBConnect.getConnection();
    PreparedStatement psm;
    String sql = "";
    public EmpManage em;
    
    public UpdateEmp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtVillage = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        rbAdmin = new javax.swing.JRadioButton();
        rbEmp = new javax.swing.JRadioButton();
        lbAddPic = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtPw = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        rbMale = new javax.swing.JRadioButton();
        rbFemale = new javax.swing.JRadioButton();
        txtCity = new javax.swing.JTextField();
        txtProvince = new javax.swing.JTextField();
        btnAddPic = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtTel = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtEmpID = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 102, 0));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Saysettha OT", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ແກ້​ໄຂ​ພະ​ນັກ​ງານ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 560, 48));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1150, 130));

        jPanel2.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtName.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jPanel2.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 207, -1));

        txtSurname.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        txtSurname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSurnameActionPerformed(evt);
            }
        });
        jPanel2.add(txtSurname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 207, -1));

        txtVillage.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        txtVillage.setText(" ");
        jPanel2.add(txtVillage, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 43, 207, -1));

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        rbAdmin.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbAdmin);
        rbAdmin.setText("Admin ");

        rbEmp.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup2.add(rbEmp);
        rbEmp.setText("Employee");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbEmp)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbAdmin)
                    .addComponent(rbEmp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, -1, -1));

        lbAddPic.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbAddPic.setText("Pic");
        lbAddPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 153), 2));
        lbAddPic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddPicMouseClicked(evt);
            }
        });
        jPanel2.add(lbAddPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 250, 250));

        txtUser.setEditable(false);
        txtUser.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jPanel2.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 331, 207, -1));

        txtPw.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        txtPw.setText(" ");
        jPanel2.add(txtPw, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 372, 207, -1));

        jLabel3.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel3.setText("ຊື່");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 100, 70, 23));

        jLabel4.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel4.setText("ນາມ​ສະ​ກຸນ");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 160, 70, -1));

        jLabel5.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel5.setText("ວ.ດ.ປ ເກີດ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 190, 70, 29));

        jLabel6.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel6.setText("ບ້ານ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 43, 34, 23));

        jLabel7.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel7.setText("ເມືອງ");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 88, 34, -1));

        jLabel8.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel8.setText("ແຂວງ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 147, -1, -1));

        jLabel9.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel9.setText("ປະ​ເພດ​ພ/ງ");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 273, 65, 40));

        jLabel10.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel10.setText("ຢູ​ສ​ເຊີ");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 331, 61, 23));

        jLabel11.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel11.setText("ລະ​ຫັດ​ຜ່ານ");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(374, 372, -1, 23));

        btnSave.setBackground(new java.awt.Color(0, 255, 255));
        btnSave.setFont(new java.awt.Font("Saysettha OT", 1, 24)); // NOI18N
        btnSave.setText("ບັນ​ທຶກ");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 147, -1));

        btnCancel.setBackground(new java.awt.Color(0, 255, 255));
        btnCancel.setFont(new java.awt.Font("Saysettha OT", 1, 24)); // NOI18N
        btnCancel.setText("ຍົກ​ເລີກ");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 147, -1));

        jDateChooser1.setBackground(new java.awt.Color(255, 153, 0));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 207, -1));

        jLabel2.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel2.setText("ເພດ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 65, 40));

        jPanel4.setBackground(new java.awt.Color(255, 153, 0));

        rbMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbMale);
        rbMale.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        rbMale.setText("ຊາຍ");
        rbMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaleActionPerformed(evt);
            }
        });

        rbFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(rbFemale);
        rbFemale.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        rbFemale.setText("ຍິງ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbMale)
                .addGap(18, 18, 18)
                .addComponent(rbFemale)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbMale)
                    .addComponent(rbFemale))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, -1, -1));

        txtCity.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jPanel2.add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 84, 207, -1));

        txtProvince.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jPanel2.add(txtProvince, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 143, 207, -1));

        btnAddPic.setBackground(new java.awt.Color(0, 255, 255));
        btnAddPic.setFont(new java.awt.Font("Saysettha OT", 0, 24)); // NOI18N
        btnAddPic.setText("ປ່ຽນ​ຮູບ​ພາບ");
        btnAddPic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPicActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel12.setText("ເບີ​ໂທ");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 184, -1, 23));

        txtTel.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jPanel2.add(txtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(845, 184, 207, -1));

        jLabel13.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jLabel13.setText("ລະ​ຫັດ");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 90, 30));

        txtEmpID.setEditable(false);
        txtEmpID.setFont(new java.awt.Font("Saysettha OT", 0, 12)); // NOI18N
        txtEmpID.setText(" ");
        jPanel2.add(txtEmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 207, 30));

        jPanel5.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 1090, 470));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 1150, 650));

        setSize(new java.awt.Dimension(1105, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtSurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSurnameActionPerformed

    private void lbAddPicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddPicMouseClicked

    }//GEN-LAST:event_lbAddPicMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            sql = "UPDATE tb_employee SET  EmpName=?, EmpSurame=?, Gender=?, DOB=?, Village=?, City=?, Province=?, Tel=?, AccountType=? where EmpId=?";;

            psm = c.prepareStatement(sql);
            psm.setString(1, txtName.getText());
            psm.setString(2, txtSurname.getText());

            String g = "";
            g = (rbMale.isSelected())?"Male":"Female";
            psm.setString(3, g);
            psm.setString(4, new SimpleDateFormat("yyyy-MM-dd").format(jDateChooser1.getDate()));
            psm.setString(5, txtVillage.getText());
            psm.setString(6, txtCity.getText());
            psm.setString(7, txtProvince.getText());
            psm.setString(8, txtTel.getText());

            String acc = "";
            acc = (rbAdmin.isSelected())?"Admin":"User";
            psm.setString(9, acc);

            psm.setInt(10, Integer.parseInt(txtEmpID.getText()));
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            ImageIO.write(bm, "jpg", out);
            byte [] pic = out.toByteArray();
            psm.setBytes(10, pic); 

           // psm.setString(11, txtUser.getText());
           // psm.setString(12, txtPw.getText());

            if(psm.executeUpdate() != -1){
                JOptionPane.showMessageDialog(this, "Saved!", "blabla", JOptionPane.INFORMATION_MESSAGE);
                //emp.showData();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed
    String path ="";
    ImageIcon icon1,icon2;
    BufferedImage bm = null;
    Image im;
    private void btnAddPicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPicActionPerformed
        try {
            JFileChooser fs = new JFileChooser();

            int r = fs.showOpenDialog(null);

            if(r==0){
                path = fs.getSelectedFile().getAbsolutePath();
                icon1 = new ImageIcon(path);
                im = icon1.getImage();
                bm = new BufferedImage(lbAddPic.getWidth(), lbAddPic.getHeight(), Image.SCALE_SMOOTH);
                bm.createGraphics().drawImage(im,0,0, lbAddPic.getWidth(), lbAddPic.getHeight(), null);
                icon2 = new ImageIcon(bm);

                lbAddPic.setIcon(icon2);
            }else if(r==1){
                return;
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAddPicActionPerformed

    private void rbMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMaleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateEmp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateEmp dialog = new UpdateEmp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddPic;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    public com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lbAddPic;
    public javax.swing.JRadioButton rbAdmin;
    public javax.swing.JRadioButton rbEmp;
    public javax.swing.JRadioButton rbFemale;
    public javax.swing.JRadioButton rbMale;
    public javax.swing.JTextField txtCity;
    public javax.swing.JTextField txtEmpID;
    public javax.swing.JTextField txtName;
    public javax.swing.JTextField txtProvince;
    public javax.swing.JTextField txtPw;
    public javax.swing.JTextField txtSurname;
    public javax.swing.JTextField txtTel;
    public javax.swing.JTextField txtUser;
    public javax.swing.JTextField txtVillage;
    // End of variables declaration//GEN-END:variables
}
